(()=>{
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const year=$('[data-year]'); if(year) year.textContent=new Date().getFullYear();
  const menu=$('.menu'), links=$('.navlinks'); if(menu&&links) menu.addEventListener('click',()=>links.classList.toggle('open'));
  $$('.navlinks a').forEach(a=>a.addEventListener('click',()=>links?.classList.remove('open')));
  const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12}); $$('.reveal').forEach(el=>io.observe(el));
  const back=$('.backtop'); if(back){addEventListener('scroll',()=>back.classList.toggle('show',scrollY>520),{passive:true});back.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));}
  $$('a[href="/descargar"],a[href="/descargar/"]').forEach(a=>a.addEventListener('click',()=>{const old=a.textContent;a.textContent='DESCARGANDO...';a.classList.add('downloading');setTimeout(()=>{a.textContent=old;a.classList.remove('downloading')},2400)}));
  if(matchMedia('(pointer:fine)').matches){const o=document.createElement('div'),i=document.createElement('div');o.className='cursor outer';i.className='cursor inner';document.body.append(o,i);let x=innerWidth/2,y=innerHeight/2,ox=x,oy=y;addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;i.style.left=x+'px';i.style.top=y+'px'});(function tick(){ox+=(x-ox)*.16;oy+=(y-oy)*.16;o.style.left=ox+'px';o.style.top=oy+'px';requestAnimationFrame(tick)})();}
  const canvas=$('#particles'); if(canvas&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const ctx=canvas.getContext('2d');let w,h,dpr,ps=[];function resize(){const r=canvas.parentElement.getBoundingClientRect();w=r.width;h=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ps=Array.from({length:34},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.18,r:Math.random()*1.7+.5}))}function draw(){ctx.clearRect(0,0,w,h);for(const p of ps){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.beginPath();ctx.fillStyle='rgba(88,217,255,.58)';ctx.shadowBlur=12;ctx.shadowColor='rgba(0,240,255,.65)';ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize,{passive:true});}
})();
